### ISSUE TITLE
Man down!

### ISSUE THREAD

**Issue by FreezePhoenix** [TheMattBat999/rpgChatGame#3]
Currently, for 332 days, I will be unable to be a Manager for the chat game. However, this will not stop me from contributing in the form of edits to the repo.

**Comment by FreezePhoenix** [comment]
@TheMattBat999  If you could get dopplegreener to investigate why I'm down, that would be awesome :)

**Comment by ghost** [comment]
Alright. I sent dopplegreener a ping.

**Comment by FreezePhoenix** [comment]
@TheMattBat999  https://chat.stackexchange.com/transcript/message/45841225#45841225 and https://discord.gg/FJjbYbw

**Comment by FreezePhoenix** [comment]
@TheMattBat999 Just one ping, don't over do it.

**Comment by FreezePhoenix** [comment]
@TheMattBat999

**Comment by FreezePhoenix** [comment]
@TheMattBat999 visit this page: https://discord.gg/3D5Jynf and follow instructions to get into the room. Then I can continue playing StardustKingoms with you guys.

**Comment by ghost** [comment]
@FreezePhoenix may I ask what you got banned for?

**Comment by FreezePhoenix** [comment]
@TheMattBat999  Entering an SO room on chat.SE

**Comment by ghost** [comment]
That is it? What room? Or more, have you went to Meta to see if you can be forgiven?

**Comment by FreezePhoenix** [comment]
@TheMattBat999 I send a request to both the SO and SE teams, and got no response. As for the room, it is 'Kappa&Yokai and Friends'

**Comment by ghost** [comment]
Well, @FreezePhoenix I tried my best to rally up attention and support but alas you will have to talk to someone at SE or a Mod if you wanna clear up this issue.

**Comment by FreezePhoenix** [comment]
@TheMattBat999 Attempting to rally attention just associated you with me. But, I appreciate the gesture, and will stay in contact when I can. You can contact me here: https://discord.gg/y8HY7JD

**Comment by ghost** [comment]
You are welcome. It will be a while before I can get on discord. Is there a way to get on their site on a mobile device without downloading the app?

**Comment by FreezePhoenix** [comment]
@TheMattBat999 https://discordapp.com/login The login page.

**Comment by ghost** [comment]
Ok I got an account (KaijZenal is the name) now what?

**Comment by ghost** [comment]
@FreezePhoenix what now?

**Comment by FreezePhoenix** [comment]
@TheMattBat999  We can talk. Communicate easier.

**Comment by FreezePhoenix** [comment]
This issue has no remaining purpose.
